DROP TABLE IF EXISTS customer;
CREATE TABLE customer(id INT, name VARCHAR(500),account_id INT, PRIMARY KEY(id));
DROP TABLE IF EXISTS customer_account;
CREATE TABLE customer_account(id INT, agencia INT,conta INT, PRIMARY KEY(id));

INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (1, 'Prof. Jarrett Wisoky', 75);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (2, 'Adelia Dicki', 16);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (3, 'Bradly Breitenberg', 78);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (4, 'Mr. Mac Oberbrunner V', 87);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (5, 'Derek Krajcik', 83);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (6, 'Maybelle Funk', 68);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (7, 'Deven Bins', 17);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (8, 'Prof. Alaina Heaney PhD', 34);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (9, 'Rosalyn Kshlerin', 59);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (10, 'Mrs. Naomie Konopelski', 69);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (11, 'Mrs. Katlyn Borer', 88);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (12, 'Kaelyn Wiegand', 20);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (13, 'Gisselle Hyatt', 74);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (14, 'Miss Katheryn Gaylord I', 46);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (15, 'Stanley Yost', 3);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (16, 'Dr. Ellie Steuber', 52);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (17, 'Octavia Langosh III', 22);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (18, 'Gerry Carroll', 85);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (19, 'Jayde Quitzon', 97);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (20, 'Alvina Schmitt IV', 60);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (21, 'Miss Pink Hauck', 12);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (22, 'Mr. Newell Hintz PhD', 93);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (23, 'Christ Trantow', 49);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (24, 'Wilmer Cummings', 73);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (25, 'Carlo Koch DVM', 6);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (26, 'Damon Haag', 86);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (27, 'Ryann Smith', 65);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (28, 'Davion Vandervort DDS', 5);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (29, 'Mrs. Loren Mills PhD', 27);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (30, 'Samanta Sawayn', 21);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (31, 'Dr. Tyson Christiansen', 64);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (32, 'Braxton OKon', 89);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (33, 'Zora Shanahan', 67);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (34, 'Dr. Ismael Larkin', 32);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (35, 'Reggie Schuppe', 56);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (36, 'Jordane Langosh', 99);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (37, 'Prof. Uriel Abshire', 44);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (38, 'Mr. Russell McLaughlin MD', 43);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (39, 'Dr. Ricardo Pouros', 90);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (40, 'Ms. Antonette Ferry Jr.', 14);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (41, 'Mrs. Lupe Cronin I', 26);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (42, 'Dr. Dewitt Wilderman DDS', 92);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (43, 'Alivia Hilpert', 55);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (44, 'Emelia Purdy', 10);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (45, 'Enrico Wolff', 18);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (46, 'Mr. Marlon Buckridge', 31);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (47, 'Mr. Gerardo Moen PhD', 13);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (48, 'Brandyn Cormier', 79);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (49, 'Davon Zieme', 2);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (50, 'Marcelo Lesch', 1);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (51, 'Abagail Sauer', 25);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (52, 'Dr. Anita Nicolas II', 38);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (53, 'Prof. Dusty Towne V', 95);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (54, 'Bradford Lockman', 91);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (55, 'Margarete Tremblay DVM', 15);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (56, 'Adrian Johns', 33);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (57, 'Marian Hegmann V', 51);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (58, 'Jackeline Von', 24);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (59, 'Miss Onie Schumm DVM', 81);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (60, 'Britney Von', 41);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (61, 'Lance Fisher', 71);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (62, 'Jordon Kuvalis', 53);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (63, 'Bianka Price', 45);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (64, 'Kenya Osinski', 40);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (65, 'Prof. Ernesto Ullrich I', 47);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (66, 'Philip Hauck', 54);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (67, 'Prof. Tanner Torphy V', 19);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (68, 'Americo Grant V', 80);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (69, 'Prof. Lauriane Lang I', 35);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (70, 'Terrence Dietrich', 63);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (71, 'Prof. Waino Crona MD', 61);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (72, 'Stan Carter V', 37);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (73, 'Foster Lubowitz III', 84);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (74, 'Miss Nicole Armstrong DDS', 72);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (75, 'Jamar Berge', 50);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (76, 'Patsy Mayert', 70);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (77, 'Hipolito Mertz', 62);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (78, 'Sonia Walsh DDS', 57);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (79, 'Alessia Erdman IV', 4);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (80, 'Prof. Trenton Beer', 36);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (81, 'Dustin Reichert', 100);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (82, 'Loraine Rolfson', 39);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (83, 'Petra Dooley', 77);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (84, 'Enrico Langosh', 9);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (85, 'Mrs. Dawn Sauer MD', 58);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (86, 'Aidan Ruecker', 29);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (87, 'Mohamed Will', 98);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (88, 'Althea Stracke', 8);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (89, 'Dr. Jamaal Hudson', 96);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (90, 'Pearline Mosciski I', 11);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (91, 'Amparo Von', 7);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (92, 'Ms. Gabrielle Lesch I', 42);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (93, 'Liliana Donnelly', 48);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (94, 'Jade Feeney', 23);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (95, 'Prof. General Kuphal', 82);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (96, 'Gail Bahringer', 94);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (97, 'Edmond Jerde', 30);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (98, 'Rupert Larson', 28);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (99, 'Karina Zieme', 76);
INSERT INTO `customer` (`id`, `name`, `account_id`) VALUES (100, 'Danielle Schamberger MD', 66);


INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (1, 9, 1);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (2, 5, 2);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (3, 4, 7);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (4, 4, 6);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (5, 8, 9);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (6, 2, 7);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (7, 5, 2);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (8, 7, 5);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (9, 6, 8);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (10, 6, 8);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (11, 5, 5);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (12, 5, 7);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (13, 9, 4);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (14, 5, 8);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (15, 1, 4);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (16, 9, 6);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (17, 2, 1);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (18, 6, 1);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (19, 1, 1);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (20, 4, 9);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (21, 1, 6);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (22, 9, 1);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (23, 2, 2);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (24, 2, 4);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (25, 9, 7);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (26, 4, 7);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (27, 1, 7);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (28, 1, 8);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (29, 1, 1);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (30, 2, 6);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (31, 9, 3);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (32, 5, 3);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (33, 5, 8);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (34, 6, 9);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (35, 7, 5);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (36, 9, 5);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (37, 6, 8);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (38, 3, 9);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (39, 3, 5);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (40, 7, 9);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (41, 4, 8);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (42, 6, 5);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (43, 7, 2);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (44, 8, 2);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (45, 8, 4);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (46, 6, 6);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (47, 6, 2);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (48, 5, 1);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (49, 6, 7);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (50, 6, 3);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (51, 8, 7);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (52, 9, 5);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (53, 8, 4);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (54, 3, 6);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (55, 7, 3);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (56, 6, 6);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (57, 8, 1);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (58, 8, 5);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (59, 4, 6);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (60, 8, 9);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (61, 7, 8);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (62, 6, 9);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (63, 7, 5);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (64, 8, 6);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (65, 1, 5);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (66, 8, 4);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (67, 9, 6);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (68, 3, 8);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (69, 3, 3);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (70, 7, 7);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (71, 3, 4);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (72, 5, 5);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (73, 7, 8);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (74, 8, 4);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (75, 4, 5);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (76, 4, 1);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (77, 3, 6);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (78, 7, 4);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (79, 5, 4);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (80, 8, 8);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (81, 3, 5);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (82, 9, 6);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (83, 8, 3);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (84, 2, 2);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (85, 6, 3);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (86, 2, 6);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (87, 9, 8);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (88, 7, 3);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (89, 2, 1);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (90, 6, 5);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (91, 4, 7);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (92, 2, 2);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (93, 2, 3);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (94, 2, 5);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (95, 9, 4);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (96, 6, 3);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (97, 4, 8);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (98, 3, 7);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (99, 6, 2);
INSERT INTO `customer_account` (`id`, `agencia`, `conta`) VALUES (100, 2, 4);